version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: local
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - .temp/data:/var/lib/mysql
      - .temp/disk:/var/lib/disk
    ports:
      - 33062:3306

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker.test
    depends_on:
      - db
    ports:
      - 30000:3000
