version: '3.8'

services:
  db:
    build: docker/db
    container_name: db-test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: local
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - .temp/data:/var/lib/mysql
      - .temp/disk:/var/lib/disk

  app:
    container_name: app-test
    build:
      context: .
      dockerfile: docker.test
    depends_on:
      - db
    ports:
      - 30000:3000
