version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: local
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./temp/mysql/data:/var/lib/mysql
      - ./temp/mysql/disk:/var/lib/disk
    ports:
      - 33062:3306

  rd:
    image: redis:6.2
    container_name: rd
    command: redis-server --port 6379
    ports:
      - 6381:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./temp/redis/data:/data

  ng:
    image: nginx
    container_name: ng
    depends_on:
      - app01
      - app02
      - app03
      - app04
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/apps.conf
    ports:
      - 30000:80

  app01:
    container_name: app01
    depends_on:
      - db
      - rd
    build:
      context: .
      dockerfile: docker.test
      args:
        - DB_SYNCHRONIZE=true
        - DB_DROP_SCHEMA=true
    ports:
      - 3001:3000

  app02:
    container_name: app02
    depends_on:
      - db
      - rd
    build:
      context: .
      dockerfile: docker.test
      args:
        - DB_SYNCHRONIZE=false
        - DB_DROP_SCHEMA=false
    ports:
      - 3002:3000

  app03:
    container_name: app03
    depends_on:
      - db
      - rd
    build:
      context: .
      dockerfile: docker.test
      args:
        - DB_SYNCHRONIZE=false
        - DB_DROP_SCHEMA=false
    ports:
      - 3003:3000

  app04:
    container_name: app04
    depends_on:
      - db
      - rd
    build:
      context: .
      dockerfile: docker.test
      args:
        - DB_SYNCHRONIZE=false
        - DB_DROP_SCHEMA=false
    ports:
      - 3004:3000
